export const whiteListendEncounterMetrics = [
    'title',
    'DURATION',
    'damage',
    'dps',
    'encdps',
    'hits',
    'crithits',
    'crithit%',
    'misses',
    'maxhit',
    'MAXHIT',
    'healed',
    'enchps',
    'critheal%',
    'maxheal',
    'maxhealward',
    'damagetaken',
    'healstaken',
    'powerdrain',
    'powerheal',
    'kills',
    'deaths',
    'CurrentZoneName',
    'Last10DPS',
    'Last30DPS',
    'Last60DPS',
]

export const whiteListCombatantMetrics = [
    'name',
    "DURATION",
    'damage',
    'damage%',
    'dps',
    'encdps',
    'hits',
    'crithits',
    'crithit%',
    'misses',
    'swings',
    'tohit',
    'maxhit',
    'MAXHIT',
    'DirectHitPct',
    'DirectHitCount',
    'CritDirectHitPct',
    'CritDirectHitCount',

    'healed',
    'healed%',
    'enchps',
    'critheals',
    'critheal%',
    'maxheal',
    'MAXHEAL',
    'maxhealward',
    'MAXHEALWARD',
    'OverHealPct',

    'damagetaken',
    'healstaken',
    'powerdrain',
    'powerheal',
    'kills',
    'deaths',
    'threatdelta',
    'Last10DPS',
    'Last30DPS',
    'Last60DPS',
    'Job',
    'ParryPct',
    'BlockPct',
]

/*
{
    "Encounter": {
      "n": "\n",
      "t": "\t",
      "title": "Encounter",
      "duration": "03:22",
      "DURATION": "202",
      "damage": "132174",
      "damage-m": "0.13",
      "damage-*": "132.17K",
      "DAMAGE-k": "132",
      "DAMAGE-m": "0",
      "DAMAGE-b": "0",
      "DAMAGE-*": "132K",
      "dps": "654.33",
      "dps-*": "dps-*",
      "DPS": "654",
      "DPS-k": "1",
      "DPS-m": "DPS-m",
      "DPS-*": "654",
      "encdps": "654.33",
      "encdps-*": "654",
      "ENCDPS": "654",
      "ENCDPS-k": "1",
      "ENCDPS-m": "0",
      "ENCDPS-*": "654",
      "hits": "67",
      "crithits": "11",
      "crithit%": "0%",
      "misses": "0",
      "hitfailed": "0",
      "swings": "67",
      "tohit": "100.00",
      "TOHIT": "100",
      "maxhit": "YOU-Storm's Path-4930",
      "MAXHIT": "YOU-4930",
      "maxhit-*": "YOU-Storm's Path-4.93K",
      "MAXHIT-*": "YOU-4930",
      "healed": "6497",
      "enchps": "32.16",
      "enchps-*": "32",
      "ENCHPS": "32",
      "ENCHPS-k": "0",
      "ENCHPS-m": "0",
      "ENCHPS-*": "32",
      "heals": "2",
      "critheals": "11",
      "critheal%": "0%",
      "cures": "0",
      "maxheal": "YOU-Storm's Path-3285",
      "MAXHEAL": "YOU-3285",
      "maxhealward": "YOU-Storm's Path-3285",
      "MAXHEALWARD": "YOU-3285",
      "maxheal-*": "YOU-Storm's Path-3.29K",
      "MAXHEAL-*": "YOU-3285",
      "maxhealward-*": "YOU-Storm's Path-3.29K",
      "MAXHEALWARD-*": "YOU-3285",
      "damagetaken": "0",
      "damagetaken-*": "0",
      "healstaken": "6497",
      "healstaken-*": "6.50K",
      "powerdrain": "0",
      "powerdrain-*": "0",
      "powerheal": "0",
      "powerheal-*": "0",
      "kills": "0",
      "deaths": "0",
      "CurrentZoneName": "Middle La Noscea",
      "Last10DPS": "650",
      "Last30DPS": "520",
      "Last60DPS": "724"
    },
    "Combatant": {
      "YOU": {
        "n": "\n",
        "t": "\t",
        "name": "YOU",
        "duration": "03:22",
        "DURATION": "202",
        "damage": "132174",
        "damage-m": "0.13",
        "damage-b": "0.00",
        "damage-*": "132.17K",
        "DAMAGE-k": "132",
        "DAMAGE-m": "0",
        "DAMAGE-b": "0",
        "DAMAGE-*": "132K",
        "damage%": "100%",
        "dps": "654.33",
        "dps-*": "654",
        "DPS": "654",
        "DPS-k": "1",
        "DPS-m": "0",
        "DPS-*": "654",
        "encdps": "654.33",
        "encdps-*": "654",
        "ENCDPS": "654",
        "ENCDPS-k": "1",
        "ENCDPS-m": "0",
        "ENCDPS-*": "654",
        "hits": "67",
        "crithits": "11",
        "crithit%": "16%",
        "crittypes": "0.0%L - 0.0%F - 0.0%M",
        "misses": "0",
        "hitfailed": "0",
        "swings": "67",
        "tohit": "100.00",
        "TOHIT": "100",
        "maxhit": "Storm's Path-4930",
        "MAXHIT": "4930",
        "maxhit-*": "Storm's Path-4.93K",
        "MAXHIT-*": "4930",
        "healed": "6497",
        "healed%": "100%",
        "enchps": "32.16",
        "enchps-*": "32",
        "ENCHPS": "32",
        "ENCHPS-k": "0",
        "ENCHPS-m": "0",
        "ENCHPS-*": "32",
        "critheals": "0",
        "critheal%": "0%",
        "heals": "2",
        "cures": "0",
        "maxheal": "Storm's Path-3285",
        "MAXHEAL": "3285",
        "maxhealward": "Storm's Path-3285",
        "MAXHEALWARD": "3285",
        "maxheal-*": "Storm's Path-3.29K",
        "MAXHEAL-*": "3.29K",
        "maxhealward-*": "Storm's Path-3.29K",
        "MAXHEALWARD-*": "3.29K",
        "damagetaken": "0",
        "damagetaken-*": "0",
        "healstaken": "6497",
        "healstaken-*": "6.50K",
        "powerdrain": "0",
        "powerdrain-*": "0",
        "powerheal": "0",
        "powerheal-*": "0",
        "kills": "0",
        "deaths": "0",
        "threatstr": "+(0)0/-(0)0",
        "threatdelta": "0",
        "NAME3": "YOU",
        "NAME4": "YOU",
        "NAME5": "YOU",
        "NAME6": "YOU",
        "NAME7": "YOU",
        "NAME8": "YOU",
        "NAME9": "YOU",
        "NAME10": "YOU",
        "NAME11": "YOU",
        "NAME12": "YOU",
        "NAME13": "YOU",
        "NAME14": "YOU",
        "NAME15": "YOU",
        "Last10DPS": "487",
        "Last30DPS": "520",
        "Last60DPS": "698",
        "Job": "War",
        "ParryPct": "0%",
        "BlockPct": "0%",
        "IncToHit": "---",
        "OverHealPct": "100%",
        "DirectHitPct": "3%",
        "DirectHitCount": "2",
        "CritDirectHitCount": "0",
        "CritDirectHitPct": "0%"
      }
    },
    "isActive": "true"
  }
  */